version: '3'

services:
  divolte:
    build:
      context: .
      dockerfile: ./docker/divolte/Dockerfile
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    restart: always
    ports:
      - "8290:8290"
    command: /opt/app/divolte-collector/bin/divolte-collector
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ./data/divolte/divolte-collector.conf:/opt/app/divolte-collector/conf/divolte-collector.conf
      - ./data/divolte/EventRecord.avsc:/opt/app/divolte-collector/conf/EventRecord.avsc
      - ./data/divolte/mapping.groovy:/opt/app/divolte-collector/conf/mapping.groovy

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "click_stream"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper
    depends_on:
      - zookeeper

  click_stream_consumer:
    image: python:3.7.0
    restart: always
    env_file:
      - click_stream_consumer.env
    working_dir: /app
    volumes:
      - ./consumer:/app
      - ./.docker/click_stream_consumer/.cache:/root/.cache
      - ./data/divolte/EventRecord.avsc:/opt/app/divolte-collector/conf/EventRecord.avsc
    command: bash -c "pip install -r /app/requirements.txt && cd /app/ && python -u sync-tool.py && python -u  click_stream_consumer.py"
    #command: bash -c "pip install -r requirements.txt && tail -f /dev/null"
    depends_on:
      - kafka
      - cassandra

  cassandra:
    image: 'bitnami/cassandra:latest'
    restart: always
    labels:
      kompose.service.type: nodeport
    ports:
      - '7000:7000'
      - '7001:7001'
      - '9042:9042'
      - '9160:9160'
